import { expect, test } from "@playwright/test";

test("clinician records a medication and normalized laboratory trends through the unified patient workflow", async ({
  page,
}) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/");
  await page.getByRole("button", { name: "Enter demo workspace" }).click();
  await page
    .getByRole("button", { name: "Register patient", exact: true })
    .click();
  await page.getByLabel("Patient display name").fill("Medication Lab Sample");
  await page.getByLabel("Synthetic MRN").fill("SYN-MEDLAB-BROWSER");
  await page.getByLabel("Birth date", { exact: true }).fill("1966-09-22");
  await page.getByLabel("Sex", { exact: true }).selectOption("Male");
  await page.getByText("Additional reusable patient details").click();
  await page.getByLabel("Height").fill("180");
  await page.getByLabel("Weight").fill("80");
  await page.getByRole("button", { name: "Create patient" }).click();

  await expect(
    page.getByRole("heading", { name: "Medication Lab Sample" }),
  ).toBeVisible();
  await expect(
    page.getByRole("heading", { name: "Medication & laboratory intelligence" }),
  ).toBeVisible();
  const intelligencePanel = page.locator("#medication-laboratory-intelligence");
  await page.getByRole("button", { name: "Add / Update" }).click();
  await page.getByRole("button", { name: /^Medication Start/ }).click();
  await page.getByLabel("Search medication").fill("Spironolactone");
  await page
    .getByRole("button", { name: /Spironolactone Steroidal MRA/ })
    .click();
  await page.getByText("HFrEF", { exact: true }).click();
  await page.getByLabel("Dose", { exact: true }).fill("25");
  await page
    .getByLabel(
      "I reviewed the current medication, reaction and monitoring context.",
    )
    .check();
  await page.getByRole("button", { name: "Confirm medication" }).click();

  await expect(
    page.getByRole("button", {
      name: "Spironolactone 25 mg · Once daily active",
    }),
  ).toBeVisible();
  await intelligencePanel
    .getByRole("button", { name: /Spironolactone 25 mg/ })
    .click();
  await page.getByRole("button", { name: "Update medication" }).click();
  await page.getByLabel("Change").selectOption("dose_decreased");
  await page.getByLabel("Dose", { exact: true }).fill("12.5");
  await page.getByRole("button", { name: "Confirm update" }).click();
  await expect(
    intelligencePanel.getByRole("button", {
      name: /Spironolactone 12.5 mg/,
    }),
  ).toBeVisible();
  await page.getByRole("button", { name: "Add / Update" }).click();
  await page.getByRole("button", { name: /^Laboratory result/ }).click();
  await page.getByLabel("Test").selectOption("potassium");
  await page.getByLabel("Value").fill("4.8");
  await page.getByRole("button", { name: "Save result" }).click();
  await expect(page.getByText("4.8", { exact: true })).toBeVisible();

  await page.getByRole("button", { name: "Add result" }).click();
  await page.getByLabel("Test").selectOption("creatinine");
  await page.getByLabel("Value").fill("88.4");
  await page.getByLabel("Original unit").selectOption("µmol/L");
  await expect(
    page.getByText(/separate 2021 CKD-EPI eGFR and Cockcroft/),
  ).toBeVisible();
  await page.getByRole("button", { name: "Save result" }).click();
  await expect(
    intelligencePanel.getByText("Creatinine", { exact: true }),
  ).toBeVisible();
  await expect(
    intelligencePanel.getByText("eGFR (2021 CKD-EPI creatinine)", {
      exact: true,
    }),
  ).toBeVisible();

  await intelligencePanel
    .getByRole("button", { name: /Spironolactone 12.5 mg/ })
    .click();
  await expect(page.getByText(/dose decreased · 12.5 mg/)).toBeVisible();
  await expect(
    page.getByText(
      "No monitoring task has been generated by a published rule.",
    ),
  ).toBeVisible();
  await expect(
    page.getByText(/Relevance mappings alone do not create clinical advice/),
  ).toBeVisible();
  await page.getByRole("button", { name: "Close dialog" }).click();

  await page.setViewportSize({ width: 1024, height: 768 });
  expect(
    await page.evaluate(() => document.documentElement.scrollWidth),
  ).toBeLessThanOrEqual(1024);
  await page.screenshot({
    path: "test-results/medication-laboratory-intelligence.png",
    fullPage: true,
    animations: "disabled",
  });
  expect(errors).toEqual([]);
});
