import { createLocalDb } from "../server/db/db.js";
import { boot } from "../server/boot.js";
import { worklist, summary, journey } from "../server/kernel/views.js";
const db = await createLocalDb();
const t0 = Date.now();
await boot(db, { seed: true });
console.log("boot ms", Date.now() - t0);
const wl = await db.transaction((tx) => worklist(tx, "sacc"));
for (const r of wl) console.log(r.name.padEnd(20), r.where.padEnd(28), (r.alert?.severity ?? "-").padEnd(7), r.alert?.title ?? "", "|", r.next?.title, r.next?.dueDate, r.next?.view);
const k = wl.find((r) => r.name.startsWith("Khaled"))!;
const s = await db.transaction((tx) => summary(tx, k.id));
console.log(JSON.stringify({ header: s.header, attention: s.attention.map((a: any) => [a.severity, a.title, a.detail, a.rule_status]), changes: s.changes, plan: s.plan.map((p) => [p.title, p.dueDate, p.view]) }, null, 1));
console.log(s.medications.groups.map((g) => g.purpose + ": " + g.meds.map((m) => `${m.name} ${m.dose} ${m.frequency} ${m.status}`).join("; ")).join("\n"));
const j = await db.transaction((tx) => journey(tx, k.id));
for (const e of j.events) console.log(e.occurred_at.slice(0, 10), e.planned ? "(planned)" : "", e.title, "|", e.detail);
const y = wl.find((r) => r.name.startsWith("Yousef"))!;
const ys = await db.transaction((tx) => summary(tx, y.id));
console.log("Yousef", JSON.stringify(ys.lvef), ys.attention.map((a: any) => a.title));
await db.close();
